add missing french sentences
OpenSourcePolitics/decidim-module-friendly_signup pull request #15
Opened 2022-12-13 14:04 UTC by eliegaboriau

related to the first item of [this notion card](https://www.notion.so/opensourcepolitics/bd4bf860eab94f9daca7da803f09e3b2?v=aed08bbf2b2e46e581cd0bfc1aefb1bb&p=188952d096844eed8b8c3acf4507bb61&pm=c)

2022-12-13 14:20 UTC, armandfardeau approved these changes

2022-12-14 16:10 UTC, armandfardeau requested changes
Please fix failing tests

2022-12-23 10:40 UTC, paulinebessoles approved these changes

2022-12-23 10:48 UTC, paulinebessoles approved these changes

2022-12-23 10:48 UTC, merged